#!/bin/bash
# Firebase Setup Checkliste

echo "🔧 Live Ticker Firebase Setup Checkliste"
echo "========================================"
echo ""
echo "Folge diesen Schritten:"
echo ""
echo "☐ 1. Firebase Project erstellen:"
echo "     https://firebase.google.com"
echo ""
echo "☐ 2. Realtime Database aktivieren (Test Mode)"
echo ""
echo "☐ 3. Service Account Key generieren:"
echo "     - Project Settings → Service Accounts → Node.js → Private Key generieren"
echo ""
echo "☐ 4. In Netlify gehen:"
echo "     - App auswählen → Site settings → Environment"
echo ""
echo "☐ 5. Diese 11 Variablen hinzufügen:"
echo "     - FIREBASE_TYPE = service_account"
echo "     - FIREBASE_PROJECT_ID = (aus JSON)"
echo "     - FIREBASE_PRIVATE_KEY_ID = (aus JSON)"
echo "     - FIREBASE_PRIVATE_KEY = (aus JSON - mit \\n)"
echo "     - FIREBASE_CLIENT_EMAIL = (aus JSON)"
echo "     - FIREBASE_CLIENT_ID = (aus JSON)"
echo "     - FIREBASE_AUTH_URI = https://accounts.google.com/o/oauth2/auth"
echo "     - FIREBASE_TOKEN_URI = https://oauth2.googleapis.com/token"
echo "     - FIREBASE_AUTH_PROVIDER_CERT_URL = https://www.googleapis.com/oauth2/v1/certs"
echo "     - FIREBASE_CLIENT_CERT_URL = (aus JSON)"
echo "     - FIREBASE_DATABASE_URL = https://YOUR-PROJECT.firebaseio.com"
echo ""
echo "☐ 6. Redeploy auf Netlify:"
echo "     - Deploys → Trigger deploy → Deploy site"
echo ""
echo "☐ 7. Test in Browser-Konsole:"
echo "     fetch('/.netlify/functions/data').then(r=>r.json()).then(console.log)"
echo ""
echo "✅ Fertig! App sollte jetzt auf allen Geräten synchronisiert sein!"
