[build]
publish = "."
functions = "netlify/functions"

[[headers]]
for = "/*.html"
[headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "no-referrer"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[redirects]]
from = "/admin"
to = "/admin.html"
status = 200

[[redirects]]
from = "/ticker"
to = "/ticker.html"
status = 200

[[redirects]]
from = "/neu"
to = "/neu.html"
status = 200